exp_info:
  model_name: "CAE"

exp_params:
  dataset: "Mastcam"
  data_path: "../../datasets/Mars_Novelty/"
  tng_dir: "train_typical"
  val_dir: "validation_typical"
  test_nov_dir: "test_novel/all"
  test_typ_dir: "test_typical"
  in_channels: 6
  hid_dim: [12,8,3]
  img_size: 64
  batch_size: 64
  LR: 0.001
  num_workers: 4
  # weight_decay: 0.0
  # scheduler_gamma: 0.95

trainer_params:
  gpus: 1
  max_nb_epochs: 20
  max_epochs: 10

logging_params:
  save_dir: "logs/"
  img_save_dir: "images/"
  name: "KernerCAE"
  manual_seed: 1265